WindowManager:
    CameraClick:
    PhotoScreen:

<CameraClick>:
    name: "camera"
    orientation: 'vertical'
    Camera:
        id: camera
        resolution: (1280, 1280)
        play: False
    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
    Button:
        text: 'Capture'
        size_hint_y: None
        height: '48dp'
        on_press: root.capture()
    Button:
        text: 'swap'
        size_hint_y: None
        height: '48dp'
        on_press: root.manager.current = "photos" 

<PhotoScreen>:
    name: "photos"
    Button:
        text: 'swap'
        size_hint_y: None
        height: '48dp'
        on_press: root.manager.current = "camera" 