<Demo>:

    MDBoxLayout:
        orientation: "vertical"
        MDToolbar:
            title: "Title"
            elevation: dp(10)
            left_action_items: [["menu", lambda x: root.callback1()]]
            right_action_items: [["dots-vertical", lambda x: root.callback2()]]
        MDBottomNavigation:

            MDBottomNavigationItem:
                name: "screen 1"
                text: "Python"
                icon: "language-python"

                MDLabel:
                    text:"Python"
                    halign:"center"

            MDBottomNavigationItem:
                name: "screen 2"
                text: "C++"
                icon: "language-cpp"

                MDLabel:
                    text:"I love C++"
                    halign:"center"

            MDBottomNavigationItem:
                name: "screen 3"
                text: "JS"
                icon: "language-javascript"

                MDLabel:
                    text:"Js"
                    halign:"center"